title = "Mon super site"
baseURL = "http://localhost:1313/"
languageCode = "en-en"
theme = "hugo-brew"

[params]
  author = "Cherel"
  description = "Une petite description cool"
  tagline = "Développeur. Designer. Penseur."
